{
  imports = [
    ./arduino-language-server.nix
    ./asm-lsp.nix
    ./basedpyright.nix
    ./deno.nix
    ./harper.nix
    ./intelephense.nix
    ./julia-languageserver.nix
    ./just-lsp.nix
    ./kotlin-language-server.nix
    ./lemminx.nix
    ./lua-language-server.nix
    ./markdown-oxide.nix
    ./marksman.nix
    ./nil.nix
    ./nimlsp.nix
    ./nixd.nix
    ./nushell.nix
    ./ocaml-lsp.nix
    ./ols.nix
    ./openscad-lsp.nix
    ./phan.nix
    ./phpactor.nix
    ./pyrefly.nix
    ./pyright.nix
    ./python-lsp-server.nix
    ./qmlls.nix
    ./r-languageserver.nix
    ./ruby-lsp.nix
    ./ruff.nix
    ./rumdl.nix
    ./solargraph.nix
    ./sqls.nix
    ./svelte-language-server.nix
    ./tailwindcss-language-server.nix
    ./taplo.nix
    ./terraform-ls.nix
    ./texlab.nix
    ./tinymist.nix
    ./tofu-ls.nix
    ./tombi.nix
    ./twig-language-server.nix
    ./ty.nix
    ./typescript-go.nix
    ./typescript-language-server.nix
    ./vala-language-server.nix
    ./wgsl-analyzer.nix
    ./yaml-language-server.nix
    ./zls.nix
    ./zuban.nix
  ];
}
